import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RouteProp } from '@react-navigation/native';

export type RootStackParamList = {
  Boarding: undefined;
  SignIn: { userType?: string } | undefined;
  SignUp: { userType?: string } | undefined;
  EmailVerification: { email: string; role: string };
  ForgotPassword: undefined;
  Notifications: undefined;
  Dashboard: undefined;
  MyInspections: undefined;
  Reports: undefined;
  InspectionStatus: undefined;
  Settings: undefined;
  AddProperty: undefined;
  RequestInspection: undefined;
  EditProperty: { property: any };
  PropertyDetails: { property: any };
  BuildingInspection: { property: any; calculatedUnits: number; selectedUnits: string[]; coverage: string };
  Analytics: undefined;
  UnitInspection: { property: any };
  AIInspection: { property: any; selectedUnits: string[]; coverage: string; totalUnits: number };
  InspectionChecklist: { property: any; unit: any };
  ManagementDashboard: undefined;
  OrderDashboard: undefined;
  NSPIREReport: { report?: any; inspectionData?: any; property?: any };
  InspectionReport: { property?: any; session?: any; findings?: any[]; images?: any[]; complianceScore?: number; overallCondition?: string };
  PropertyInfo: { property: any; selectedUnits: string[]; completedUnits?: string[]; buildingId?: string };
  InspectionCategories: { property: any; selectedUnits: string[]; buildingId: string; currentUnit?: string; propertyId?: string };
  UnitLocations: { property: any; selectedUnits: string[]; buildingId: string };
  LocationInspection: { property: any; selectedUnits: string[]; buildingId: string; location: string; currentUnit?: string };
  DeficiencyDetail: { 
    property: any; 
    selectedUnits: string[]; 
    buildingId: string; 
    location: string; 
    itemId: string;
    itemName: string;
    currentUnit?: string;
  };
  InspectionSummary: {
    property: any;
    selectedUnits: string[];
    buildingId: string;
    inspectionData: any;
    currentUnit?: string;
    allUnits?: string[];
    inspectionId?: string;
  };
};

export type BoardingScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'Boarding'>;
export type SignInScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'SignIn'>;
export type SignInScreenRouteProp = RouteProp<RootStackParamList, 'SignIn'>;
export type SignUpScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'SignUp'>;
export type SignUpScreenRouteProp = RouteProp<RootStackParamList, 'SignUp'>;
export type EmailVerificationScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'EmailVerification'>;
export type EmailVerificationScreenRouteProp = RouteProp<RootStackParamList, 'EmailVerification'>;
export type DashboardScreenNavigationProp = NativeStackNavigationProp<RootStackParamList, 'Dashboard'>;
